name: 'Create Pull request to Main'

on:
  workflow_call:
  # push:
  #   branches:
  #     - develop
  # schedule:
  #   - cron: "0 8 * * 1,2,3,4,5" # UTC timezone which is 8am; 4pm in Singapore

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop
      - name: create pull request to main branch
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.FULL_PAT }} # personal access token. Permissions contents: write, pull requests: write
          branch: prod-promotion
          title: Merge Develop to Main
          labels: |
            automated pr
