name: Automerge to Main Branch

on:
  workflow_call:
  workflow_dispatch:  # remove this (for testing)

jobs:
  automerge:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Set up Git
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge release branch into main
        run: |
          git --version
          git config --global user.email "you@example.com"
          git config --global user.name "Auto Merger"
          git fetch origin
          git checkout release
          git pull origin release
          git checkout main
          git pull origin main

          git status
          git config --list

          git merge --squash release -m "Automerge: Merge release into main" --allow-unrelated-histories -s theirs --verbose
          git push origin main
        env:
          GH_TOKEN: secrets.GITHUB_TOKEN
