name: Automerge to Main Branch

on:
  workflow_call:

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge release branch into main
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Auto Merger"
          git fetch origin
          git checkout main
          git merge --no-ff release -m "Automerge: Merge release into main" --allow-unrelated-histories
          git push origin main
        env:
          GH_TOKEN: secrets.GITHUB_TOKEN
