name: Automerge to Main Branch

on:
  workflow_call:
  workflow_dispatch:  # remove this (for testing)

jobs:
  automerge:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge release branch into main
        run: |
          git --version
          git config --global user.email "you@example.com"
          git config --global user.name "Auto Merger"
          git fetch origin
          git checkout release
          git pull origin release
          git checkout main
          git pull origin main
          git merge --squash release -m "Automerge: Merge release into main"
          git push origin main
        env:
          GH_TOKEN: secrets.GITHUB_TOKEN
