name: app-build
on:
  workflow_dispatch:
  pull_request:     # when hotfix PR is merged in main
    branches:
      - 'main'
    types:
      - closed
  push:             # push to develop branch
    branches:
      - develop
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.event.pull_request.merged == true && github.base_ref == 'refs/heads/main' || contains(github.ref, 'fix-') || contains(github.ref, 'feat-')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          echo "Build the image"

  set-tag:
    needs: [build]
    # set tag only for develop or hotfix build
    if: github.ref == 'refs/heads/develop' || github.event.pull_request.merged == true && github.base_ref == 'refs/heads/main'
    uses:  ./.github/workflows/tag-setter.yml
