name: app-build
on:
  workflow_dispatch:
  # pull_request:     # when pr is opened from hotfix branch
  #   branches:
  #     - 'main'
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          echo "Build the image"
  set-tag:
    needs: [build]
    if: github.head_ref == 'refs/heads/develop'
    uses:  ./.github/workflows/tag-setter.yml
