name: app-build
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - develop


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
