name: deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - production
          # - isd-development
          # - development
  # push:
  #   branches:
  #     - develop
  #     - release
permissions:
  contents: write

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy development
        run: echo "deployed on development"
  deploy-stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Deploy staging
        run: echo "deployed on staging"
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && inputs.environment == 'production'
    steps:
      - name: Deploy Prod
        run: |
          echo "github.actor: ${{ github.actor }}"
          echo "github.actor.role: ${{ github.actor.role }}"
          echo "deployed on production"

  e2e:                              # run e2e on successfull stage deployment
    needs: [deploy-stage]
    if: needs.deploy-stage.result == 'success'
    uses: ./.github/workflows/e2e.yml
    with:
      stage_deployment_success: true
