name: deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - production
          - isd-development
          - pi-development

permissions:
  contents: write

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy development
        run: |
          echo "Deploying on ${{ needs.determine-environment.outputs.selected-env }}"
          echo "Deploying commit: ${{ vars.IMAGE_TAG }}"

  e2e:                              # run e2e on successfull stage deployment
    needs: [deploy-stage]
    if: needs.deploy-stage.result == 'success'
    uses: ./.github/workflows/e2e.yml
    with:
      stage_deployment_success: true

  release:
    needs: [deploy-prod]
    if: needs.deploy-prod.result == 'success'
    uses: ./.github/workflows/release.yml
