name: deploy
on:
  workflow_call:                # auto deploy to staging
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:            # manual deploy to production / dev envs
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - production
          - development
          - isd-development
          - pi-development
          - user-development
          - discovery-development
          - se-development

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          echo "Deploying on ${{ inputs.environment }}"
          echo "Deploying sha:   ${{ env.sha }}"
        env:    # read IMAGE_TAG for prod. read current commit-sha for others
          sha: ${{ inputs.environment != 'production' && github.sha || vars.IMAGE_TAG }}

  e2e:                              # run e2e once deployed to staging
    needs: [deploy]
    if: inputs.environment == 'staging' && needs.deploy.result == 'success'
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  release:                          # once deployed to production
    needs: [deploy]
    if: inputs.environment == 'production' && needs.deploy.result == 'success'
    uses: ./.github/workflows/release.yml
