name: deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  # workflow_dispatch:
  #   inputs:
  #     environment:
  #       description: 'Environment to deploy to'
  #       required: true
  #       type: choice
  #       options:
  #         - isd-development
  #         - development
  #         - production
  # push:
  #   branches:
  #     - develop
  #     - release

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy development
        run: echo "deployed on development"
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy staging
        if: github.ref == 'refs/heads/release'
        run: echo "deployed on staging"
  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Prod
  #       if: github.ref == 'refs/heads/main'
  #       run: echo "deployed on staging"


  e2e:                              # run e2e on successfull stage deployment
    needs: [deploy-stage]
    if: needs.deploy-stage.result == 'success'
    uses: ./.github/workflows/e2e.yml
    with:
      stage_deployment_success: true
