name: 'Merge Enforcer'

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  mergeability:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && !contains(github.head_ref, 'hotfix-') || github.head_ref != 'develop'
    steps:
      - run: |
          echo "ERROR: You can only merge to main from dev or hotfix."
          exit 1
