name: Manual Merge

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Merge to?'
        required: true
        default: 'release'
        type: choice
        options:
        - release

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge develop into release
        run: |
          git fetch origin
          git checkout release
          git merge origin/develop --no-ff --no-edit
          git push origin release
