name: Manual Merge

on:
  workflow_dispatch:
    inputs:
      to-branch:
        description: 'Merge to?'
        required: true
        default: 'release'
        type: choice
        options:
        - release

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Manually merge a branch
        run: |
          git fetch origin
          git checkout ${{ inputs.to-branch }}
          git merge origin/${{ github.ref_name }} --no-ff --no-edit
          git push origin ${{ inputs.to-branch }}
        env: 
          GH_TOKEN: secrets.GITHUB_TOKEN
