name: Manual Merge

on:
  workflow_dispatch:
    inputs:
      to-branch:
        description: 'Merge to?'
        required: true
        default: 'release'
        type: choice
        options:
        - release

jobs:
  merge:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: secrets.GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if merge is needed
        id: check-merge
        run: |
          git fetch origin
          if [ "$(git rev-parse origin/${{ github.ref_name }})" != "$(git rev-parse origin/${{ inputs.to-branch }})" ]; then
            echo "::set-output name=merge_needed::true"
          else
            echo "::set-output name=merge_needed::false"
          fi

      - name: Manually merge a branch
        if: steps.check-merge.outputs.merge_needed == 'true'
        id: perform-merge
        run: |
          git fetch origin ${{ inputs.to-branch }} ${{ github.ref_name }}
          git checkout ${{ inputs.to-branch }}
          echo "Merging ${{github.ref_name}} into ${{ inputs.to-branch }}"
          git config --global user.email "you@example.com"
          git config --global user.name "Automerger"
          git merge ${{ github.ref_name }} --allow-unrelated-histories
          git push origin ${{ inputs.to-branch }}
