name: Post merge to main

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  set-prod-tag:     # In case develop is merged in main
    if: contains(github.head_ref, 'prod-promotion') && github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PUBLIC_REPO }}
          event-type: set-prod-tag
          client-payload: '{"env": "production"}'

  set-prod-tag-for-hotfix:      # when hotfix pr is merged in main
    if: contains(github.head_ref, 'hotfix-') && github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PUBLIC_REPO }}
          event-type: set-prod-tag
          client-payload: '{"env": "hotfix-to-prod-tag"}'
