name: tag-seter
on:
  push:               # runs when pushed to release
    branches:
      - release
  repository_dispatch:        # auto-merge case - main & develop
    types: [set-prod-tag, set-dev-tag]

permissions:
  contents: write

jobs:
  dev-image-tag:
    if: ${{ github.event.client_payload.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env development
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  stage-image-tag:
    if: github.event.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env staging
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  production-image-tag:
    if: ${{ github.event.client_payload.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env production
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  deploy_development:
    needs: [dev-image-tag]
    if: needs.dev-image-tag.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  deploy_staging:               # once the tag is set, auto deploy using set tag.
    needs: [stage-image-tag]
    if: needs.stage-image-tag.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
