name: tag-seter
on:
  # workflow_run:       # run when build is success for develop & hotfix case
  #   workflows: [app-build]
  #   types: [completed]
  #   branches: ['refs/heads/main', 'refs/heads/develop']
  push:               # runs when pushed to release
    branches:
      - release
  repository_dispatch:
    types: [set-for-hotfix, set-for-develop]

permissions:
  contents: write

jobs:
  dev:
    if: ${{ github.event.client_payload.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: gh
      #   run: |
      #     gh variable list
      #     gh variable set DEV_IMAGE_TAG --body ${{ github.sha }}
      #     gh variable list
      #   env:
      #     GH_TOKEN: ${{ secrets.FULL_PAT }}
      - name: update Image Tag ENV value
        run: |
          echo "Setting gh variable"
          echo "Setting DEV_IMAGE_TAG as ${{ github.event.client_payload.sha }}"

  stage:
    if: github.event.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: update Image Tag ENV value
        uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
          token: ${{ secrets.FULL_PAT }}
          repository: ${{ github.repository }}
          name: STAGE_IMAGE_TAG
          value: 'a value'
      - name: gh
        run: |
          gh variable list
          gh variable set STAGE_IMAGE_TAG --body ${{ github.sha }}
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}
      - name: update Image Tag ENV value echo
        run: |
          echo "Setting gh variable"
          echo "Setting STAGE_IMAGE_TAG as ${{ github.sha }}"

  production:
    if: ${{ github.event.client_payload.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      # - name: update Image Tag ENV value
      #   uses: mmoyaferrer/set-github-variable@v1.0.0
      #   with:
      #     token: ${{ secrets.GH_TOKEN_SEPHORA_BOT }}
      #     repository: ${{ github.repository }}
      #     name: PROD_IMAGE_TAG
      #     value: ${{ env.IMAGE_TAG }}
      - name: update Image Tag ENV value
        run: |
          echo "Setting gh variable"
          echo "Setting PROD_IMAGE_TAG as ${{ github.event.client_payload.sha }}"

  deploy_development:
    needs: [dev]
    if: needs.dev.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  deploy_staging:               # once the tag is set, auto using set tag.
    needs: [stage]
    if: needs.stage.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
