name: tag-seter
on:
  # workflow_run:       # run when build is success for develop & hotfix case
  #   workflows: [app-build]
  #   types: [completed]
  #   branches: ['refs/heads/main', 'refs/heads/develop']
  push:               # runs when pushed to release
    branches:
      - release
  repository_dispatch:
    types: [set-prod-tag, set-dev-tag]

permissions:
  contents: write

jobs:
  dev:
    if: ${{ github.event.client_payload.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env development
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  stage:
    if: github.event.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env staging
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  production:
    if: ${{ github.event.client_payload.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v4
      - name: gh
        run: |
          gh variable list
          gh variable set IMAGE_TAG --body ${{ github.sha }} --env production
          gh variable list
        env:
          GH_TOKEN: ${{ secrets.FULL_PAT }}

  deploy_development:
    needs: [dev]
    if: needs.dev.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  deploy_staging:               # once the tag is set, auto deploy using set tag.
    needs: [stage]
    if: needs.stage.result == 'success'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
