name: Unit Test Workflow

on:
  pull_request:
    branches:
      - develop
    types:
      - opened

jobs:
  unit_tests:
    if: startsWith(github.head_ref, 'fix-') || startsWith(github.head_ref, 'feat-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          echo "Testing code"
