name: Unit Test Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - 'develop'

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          echo "Testing code"
