name: Unit Test Workflow

on:
  pull_request:
    types:
      - opened
    branches:
      - 'develop'
      - 'main'

jobs:
  unit_tests:
    if: startsWith(github.head_ref, 'fix-') || startsWith(github.head_ref, 'feat-') || startsWith(github.head_ref, 'hotfix-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          echo "Testing code"
